export * from './home/Home';
export * from './about/About';
export * from './services/Services';
export * from './contact/Contact';
export * from './auth/Auth';
export * from './notFound/NotFound';
export * from './profile/Profile';
export * from './serviceDetails/ServiceDetails';
export * from './forgotPassword/ForgotPassword';